### ISSUE TITLE
duplicate method in the controller is missing the return data

### ISSUE THREAD

**Issue by icampana** [impresspages-plugins/GridWidget#2]
The duplicate method doesn't have a propper return value, even when the documentation states it.  So, if you add configuration options to your widget, when you click the publish button (and IP generates a new content revision all your options dissapear, as they are not passed on to the new revision).

As this Widget is supposed to work as a "guide" to create new widgets, it could represent a problem (took me a couple hours to figure it out as a newbie to IP).

The solution is to add a this after line 43 on the file Widget/GridWidget/Controller.php:
return $data;

**Comment by maskas** [comment]
You are a great developer. Thanks for reporting!

**Comment by icampana** [comment]
You're welcome! Thanks for making such a great tool! Hope to help you again later :+1:
